### ISSUE TITLE
Tires spinning in the mud

### ISSUE THREAD

**Issue by deathbybandaid** [MilesGG/Pi-Hole-Summary#1]
I'm not overly familiar with node,,,, This is spitting out when I just try to run the index.js

Anything I should be looking at?

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

**Comment by MilesGG** [comment]
This is an error created by the `http` package, are you running the pi-hole server on the same device as the script and on port 80?

If you want a special setup on your network just replace `http://127.0.0.1/admin/api.php` with something like `http://192.168.1.X/admin/api.php` where X is the final ip address number. You can swap the port with `192.168.1.X:Y` where Y is the port number, usually 80.

**Comment by deathbybandaid** [comment]
I tried switching it from 127.0.0.1 to localhost.

I have lighttpd on a vlan ip of 192.168.1.99, and nginx as a reverse proxy on 192.168.1.100.

Nginx uses the /admin proxied. ,,,, And everything else I have set to do API calls works when I specify localhost.

I'll try setting a specific IP address later.

Does node not like using localhost or something?

**Comment by deathbybandaid** [comment]
Awesome! That worked!!!!

I have been building 

https://github.com/deathbybandaid/piadvanced

A script to install stuff like this. It uses whiptail to ask for the config information.

I will give credit to your repo within my README.md

Not trying to steal anybody's work. I've been working with a bunch of people on Reddit and the pihole-discourse server to find the best add-ons to pihole. Yours, I just searched GitHub for the term pihole.

**Comment by deathbybandaid** [comment]
One last note,,, besides specifying the IP address, I found another fix,,,, you can put 

pi.hole

I think that works even better.
